name: Proxy Cleaner

on:
  workflow_dispatch:

jobs:

  clean:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v5


    - name: Download subscription
      run: |
        wget "${{ secrets.GIST_URL }}" -O source.yaml
        ls -lh source.yaml


    - name: Install Mihomo
      run: |
        wget https://github.com/MetaCubeX/mihomo/releases/latest/download/mihomo-linux-amd64 -O mihomo
        chmod +x mihomo
        ./mihomo -v


    - name: Install Python
      run: |
        pip install pyyaml


    - name: Count nodes
      run: |
        python3 - <<EOF
        import yaml

        with open("source.yaml","r",encoding="utf-8") as f:
            data=yaml.safe_load(f)

        print("当前节点:")
        print(len(data["proxies"]))
        EOF
