name: Proxy Cleaner Test

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v5

    - name: Show system
      run: |
        echo "GitHub Actions OK"
        uname -a
