name: Clean VIP Nodes

on:
  schedule:
    - cron: "0 */4 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  clean:
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests pyyaml

      - name: Run clean.py
        run: |
          python clean.py

      - name: Show result
        run: |
          echo "======================================"
          echo "最终 cleanvip.yaml"
          echo "======================================"

          if [ -f cleanvip.yaml ]; then
            cat cleanvip.yaml
          else
            echo "没有生成 cleanvip.yaml"
          fi

      - name: Commit cleanvip.yaml
        run: |

          if [ ! -f cleanvip.yaml ]; then
            echo "没有生成文件，不提交"
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"

          git add cleanvip.yaml

          if git diff --cached --quiet; then
            echo "cleanvip.yaml 没有变化"
          else
            git commit -m "Auto update cleanvip.yaml"
            git push
          fi
