      # ============================================
      # 7. 提交
      # ============================================

      - name: Commit cleanvip.yaml
        run: |

          if [ ! -f cleanvip.yaml ]; then

            echo "======================================"
            echo "没有生成 cleanvip.yaml"
            echo "本轮不提交任何文件"
            echo "======================================"

            exit 0

          fi


          git config user.name "github-actions[bot]"

          git config user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"


          git add cleanvip.yaml


          if git diff --cached --quiet; then

            echo "cleanvip.yaml 没有变化"

          else

            git commit \
              -m "Auto update cleanvip.yaml"

            git push

          fi
